-- COMANDOS PARA CRIAR UM BANCO DE DADOS

-- 1
-- CREATE DATABASE ESCOLA_FRANZ;
-- CREATE DATABASE ESCOLA_FRANZ2;




-- COMANDO PARA APAGAR UM BANCO DE DADOS

-- DROP DATABASE ESCOLA_FRANZ2;

-- COMANDO PARA ATIVAR BANCO DE DADOS

-- USE ESCOLA_FRANZ;
-- ====================================================================================================================================
-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS GESTAO_ESCOLAR (
ID_GESTAO INT AUTO_INCREMENT PRIMARY KEY,
OCORRENCIAS VARCHAR(100),
FINANCEIRO INT,
EVENTOS CHAR(15),
CARGO ENUM ('SECRETARIA', 'ORIENTADOR ESCOLAR', 'DIRETOR', 'COORDENADOR')

);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
CARGO ENUM ('PROFESSORES', 'PORTARIA', 'LIMPEZA', 'INSPETORES') NOT NULL,
ESPECIALIDADE VARCHAR(20), 
BLOCO CHAR(7) NOT NULL,
NOME_FUNCIONARIO VARCHAR(40) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
SALARIO DECIMAL(5,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME_ALUNO VARCHAR(40) NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
SERIE CHAR(10) NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_ALUNO ENUM ('ATIVO' , 'INATIVO') DEFAULT 'ATIVO',
RM INT NOT NULL 

);

-- ALTERAR INFORMAÇÕES DA TABELA

-- ALTER TABLE 
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
-- ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100);

-- ALTERAR TIPO DE DADOS DE UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA
-- ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIO;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE FUNCIONARIO;

-- APAGAR BCD
DROP DATABASE ESCOLA_FRANZ;

-- APAGAR TABELAS
DROP TABLES FUNCIONARIO;

-- MOSTRAR TABELAS NO BCD
SHOW TABLES ;

-- ==============================================================================================================================================

-- INSERIR DADOS NO BCD
INSERT INTO FUNCIONARIO (ID_FUNCIONARIO,CARGO,ESPECIALIDADE,BLOCO,NOME_INSPETOR)
VALUES (6, 'LIMPEZA', 'FACULDADE', 'BLOCO 3', 'JULIA'),
(4, 'INSPETORES', 'TECNOLOGIA', 'BLOCO 5', 'GABRIEL');

-- CONSULTAR DADOS NO BCD
SELECT * FROM FUNCIONARIO;

-- MOSTRAR TODOS OS BANCOS DE DADOS
-- SHOW DATABASES;

 INSERT INTO ALUNOS (ID_ALUNO, NOME_ALUNO, CPF, SERIE, DATA_CADASTRO, STATUS_ALUNO, RM)
 VALUES(DEFAULT, 'GABRIEL', '902.025.868-92', '2', DEFAULT, DEFAULT, '2917');
 
 SELECT * FROM ALUNOS;

truncate TABLE FUNCIONARIO;























