-- COMANDOS PARA CRIAR UM BANCO DE DADOS

-- 1
-- CREATE DATABASE ESCOLA_FRANZ;
-- CREATE DATABASE ESCOLA_FRANZ2;


-- COMANDO PARA APAGAR UM BANCO DE DADOS

-- DROP DATABASE ESCOLA_FRANZ2;

-- COMANDO PARA ATIVAR BANCO DE DADOS

-- USE ESCOLA_FRANZ;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS GESTAO_ESCOLAR (
ID_GESTAO INT AUTO_INCREMENT PRIMARY KEY,
OCORRENCIAS VARCHAR(100),
FINANCEIRO INT,
EVENTOS CHAR(15),
CARGO ENUM ('SECRETARIA', 'ORIENTADOR ESCOLAR', 'DIRETOR', 'COORDENADOR')

);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
CARGO ENUM ('PROFESSORES', 'PORTARIA', 'LIMPEZA', 'INSPETORES') NOT NULL,
ESPECIALIDADE VARCHAR(20), 
BLOCO CHAR(7) NOT NULL,
NOME_FUNCIONARIO VARCHAR(40) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
SALARIO DECIMAL(5,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME_ALUNO VARCHAR(40) NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
SERIE CHAR(10) NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_ALUNO ENUM ('ATIVO' , 'INATIVO') DEFAULT 'ATIVO',
RM INT NOT NULL 

);

-- ALTERAR INFORMAÇÕES DA TABELA

-- ALTER TABLE 
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
-- ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100);

-- ALTERAR TIPO DE DADOS DE UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA
-- ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIO;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE FUNCIONARIO;

-- APAGAR BCD
DROP DATABASE ESCOLA_FRANZ;

-- APAGAR TABELAS
DROP TABLES FUNCIONARIO;

-- MOSTRAR TABELAS NO BCD
SHOW TABLES ;

