-- PROJETO SMARTCOFFEE_FRANZ

-- CRIAR BCD
-- ATIVAR BCD
-- CRIAR TABELAS

-- INSERIR DADOS
-- CONSULTAR DADOS

CREATE DATABASE SMARTCOFFE_FRANZ;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
IDADE INT,
NASCIMENTO DATE NOT NULL,
NUMERO_TELEFONE VARCHAR (15) UNIQUE,
CIDADE CHAR(20)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
ID_PRODUTO INT AUTO_INCREMENT primary key,
NOME_PRODUTO VARCHAR(60) NOT NULL,
TAMANHO ENUM ('P','M','G') DEFAULT 'M',
TIPO VARCHAR(30) NOT NULL,
QUANTIDADE INT NOT NULL,
VALOR DECIMAL(3,1) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
SALARIO DECIMAL(5,2) DEFAULT 0.00,
ESPECIALIDADE VARCHAR(40) NOT NULL,
NASCIMENTO DATE NOT NULL,
SETOR CHAR(10) NOT NULL
)