-- Active: 1788519228847@@127.0.0.1@3306@smartcoffee_franz01
-- Gera��o de Modelo f�sico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE IF NOT EXISTS Fornecedor (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(30),
TIPO_FORNECEDOR VARCHAR(30),
DATA_FORNECIMENTO DATE,
TELEFONE VARCHAR(14),
PRODUTO_FORNECIDO ENUM ('CAFE', 'BEBIDAS', 'SALGADOS', 'DOCES') DEFAULT 'CAFE'

)

CREATE TABLE Categoria(
MARCA CHAR(10),
ID_CATEGORIA INT AUTO_INCREMENT UNIQUE,
FAIXA_VALOR DECIMAL(5,2),
QUANTIDADE_ESTOQUE INT,
TAMANHO ENUM('P', 'M', 'G') NOT NULL,
TIPO_PRODUTO ENUM ('CAFE', 'BEBIDAS', 'SALGADOS', 'DOCES') DEFAULT 'CAFE'
)


CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PRODUTO VARCHAR(60) NOT NULL,
DESCRICAO_PRODUTO VARCHAR (255),
PRECO_UNITARIO DECIMAL (5,2) NOT NULL,
QUANTIDADE_ESTOQUE INT NOT NULL,
CATEGORIA CHAR(20) NOT NULL,
TAMANHO ENUM('P', 'M', 'G') NOT NULL,
VALIDADE DATE NOT NULL,
ID_FORNECEDOR INT,
-- PRIMARY KEY(ID_CATEGORIA,ID_PRODUTO),
FOREIGN KEY(ID_FORNECEDOR) REFERENCES Fornecedor (ID_FORNECEDOR)
)

CREATE TABLE Estoque (
Valor DECIMAL(5,2),
NOME_INSUMO VARCHAR(20),
ID_INSUMO INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
TAMANHO ENUM('P', 'M', 'G') NOT NULL,
QUANTIDADE_ATUAL INT,
TIPO_INSUMO ENUM('CAFE', 'BEBIDAS', 'SALGADOS', 'DOCES') DEFAULT 'CAFE',
QUANTIDADE_MINIMA INT,
UNIDADE_MEDIDA ENUM('KG', 'ML', 'UN') DEFAULT 'KG'
)

CREATE TABLE IF NOT EXISTS Delivery (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
Quantidade INT,
Previsao_Entrega DATE,
TAXA_ENTREGA DECIMAL(5,2),
ENDERECO_ENTREGA VARCHAR(40) NOT NULL,
Nome_Cliente VARCHAR(30)NOT NULL,
Nome_Produto VARCHAR(30) NOT NULL,
DATA_HORA_SAIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_ENTREGA VARCHAR(40) NOT NULL
);

CREATE TABLE CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT UNIQUE,
NOME_CLIENTE VARCHAR(60) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
IDADE_CLIENTE INT,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CIDADE_CLIENTE VARCHAR(60),
ESTADO_CLIENTE CHAR(2),
NUMERO_TELEFONE CHAR(15) NOT NULL UNIQUE,
CPF VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(30) UNIQUE
)

CREATE TABLE PROGRAMA_FIDELIDADE (
Desconto DECIMAL(5,2),
Nome VARCHAR(30),
Valor DECIMAL (5,2),
SALDO_PONTOS INT NOT NULL,
Quantidade_Produtos INT NOT NULL,
ID_FIDELIDADE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Pontos_Restantes INT NOT NULL,
DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO DECIMAL(10),
CARGO VARCHAR(30) NOT NULL,
SALARIO DECIMAL (10, 2) NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
SETOR VARCHAR(30) NOT NULL,
ESPECIALIDADE VARCHAR(20) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE
)

CREATE TABLE PEDIDOS(
ID_PEDIDO INT AUTO_INCREMENT UNIQUE,
DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
QUANTIDADE INT NOT NULL,
PREVISAO_ENTREGA DATE NOT NULL,
VALOR_TOTAL DECIMAL (5,2) NOT NULL,
STATUS_PEDIDO ENUM('PENDENTE', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL,
HISTORICO_PEDIDOS ENUM('FINALIZADO', 'REEMBOLSADO', 'ENTREGUE') NOT NULL,
TIPO_PEDIDO ENUM('PRESENCIAL', 'DELIVERY') NOT NULL
)



CREATE TABLE PAGAMENTO (
TIPO_PAGAMENTO ENUM('PIX', 'CARTAO', 'DINHEIRO') NOT NULL,
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
NOTA_FISCAL VARCHAR(20) NOT NULL,
NOME_CLIENTE VARCHAR(60) NOT NULL,
VALOR_PAGO DECIMAL(5,2) NOT NULL,
DATA_HORA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_PAGAMENTO CHAR(20) NOT NULL
-- ID_PEDIDO INT,
-- PRIMARY KEY(ID_PEDIDO,ID_PAGAMENTO)
)

CREATE TABLE Contem(
ID_PEDIDO INT,
ID_PRODUTO INT,
Quantidade INT,
preco_historico DECIMAL(5,2),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)
)

CREATE TABLE ATENDE (
ID_FUNCIONARIO INT,
ID_PEDIDO INT,
ID_PAGAMENTO INT,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
FOREIGN KEY(ID_PAGAMENTO) REFERENCES PAGAMENTO (ID_PAGAMENTO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
)

CREATE TABLE Entrega (
ID_FUNCIONARIO INT,
ID_PEDIDO INT,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
)

CREATE TABLE REALIZA (
ID_PEDIDO INT,
ID_PAGAMENTO INT,
ID_CLIENTE INT,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
FOREIGN KEY(ID_PAGAMENTO) REFERENCES PAGAMENTO (ID_PAGAMENTO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
)

CREATE TABLE Consome(
ID_INSUMO INT,
ID_PRODUTO INT,
quantidade_gasta INT,
FOREIGN KEY(ID_INSUMO) REFERENCES Estoque (ID_INSUMO),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)
)

ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_PAGAMENTO) REFERENCES PAGAMENTO (ID_PAGAMENTO)
