CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    IDADE_CLIENTE INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CIDADE_CLIENTE VARCHAR(60),
    ESTADO_CLIENTE CHAR(2),
    NUMERO_TELEFONE CHAR(15) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(60) NOT NULL,
    DESCRICAO_PRODUTO VARCHAR(255),
    VALOR DECIMAL(5, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    CATEGORIA CHAR(20) NOT NULL,
    TAMANHO ENUM('P', 'M', 'G') NOT NULL,
    VALIDADE DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
    CARGO VARCHAR(30) NOT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    SETOR VARCHAR(30) NOT NULL,
    ESPECIALIDADE VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL

);

CREATE TABLE IF NOT EXISTS PEDIDOS(
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL DECIMAL(5, 2) NOT NULL,
    STATUS ENUM('PENDENTE', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL,
    PREVISAO_ENTREGA DATE NOT NULL,
    HISTORICO_PEDIDOS ENUM ('FINALIZADO', 'REEMBOLSADO', 'ENTREGUE') NOT NULL
);

CREATE TABLE IF NOT EXISTS PAGAMENTO(
    
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOTA_FISCAL VARCHAR(20) NOT NULL,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    VALOR DECIMAL(5, 2) NOT NULL,
    STATUS_PAGAMENTO ENUM('PENDENTE', 'APROVADO', 'RECUSADO') NOT NULL,
    DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FORMA_PAGAMENTO ENUM('CARTÃO DE CRÉDITO', 'CARTÃO DE DÉBITO', 'PIX', 'DINHEIRO') NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUE(

    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(60) NOT NULL,
    TAMANHO ENUM('P', 'M', 'G') NOT NULL,
    TIPO_PRODUTO ENUM('CAFÉ', 'BEBIDAS', 'SALGADOS', 'DOCES') NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    VALOR DECIMAL(5, 2) NOT NULL,
    DATA_VALIDADE DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS DELIVERY(
    
    ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    ENDERECO_ENTREGA VARCHAR(100) NOT NULL,
    DATA_ENTREGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_ENTREGA ENUM('PENDENTE', 'EM ANDAMENTO', 'ENTREGUE', 'CANCELADO') NOT NULL,
    NOME_PRODUTO VARCHAR(60) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_TOTAL DECIMAL(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROGRAMA_FIDELIDADE(
    ID_PROGRAMA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    PONTOS_ACUMULADOS INT NOT NULL,
    DATA_ULTIMA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUANTIDADE_PRODUTOS INT NOT NULL,
    STATUS_PROGRAMA ENUM('ATIVO', 'INATIVO') NOT NULL,
    VALOR DECIMAL(5, 2) NOT NULL,
    DESCONTO DECIMAL(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(30) NOT NULL,
    TIPO_PRODUTO ENUM('CAFÉ', 'BEBIDAS', 'SALGADOS', 'DOCES') NOT NULL,
    MARCA VARCHAR(30) NOT NULL,
    TAMANHO ENUM('P', 'M', 'G') NOT NULL,
    FAIXA_VALOR DECIMAL(5, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL

);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(60) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    DATA_FORNECIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_PRODUTO ENUM('CAFÉ', 'BEBIDAS', 'SALGADOS', 'DOCES') NOT NULL
);