-- Comando criar Banco de Dados
CREATE DATABASE ESTACIONAMENTO_SENAI;

-- Comando criar tabelas
CREATE TABLE CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
NOME VARCHAR(60),
CPF VARCHAR(14),
TELEFONE VARCHAR(14),
NASCIMENTO VARCHAR(10),
ENDERECO VARCHAR(60)

);

CREATE TABLE VEICULOS(
ID_VEICULO INT PRIMARY KEY,
PLACA VARCHAR (10),
MODELO VARCHAR (10),
N_VAGA INT,
TIPO VARCHAR(10)

);

-- Comando excluir Banco de Dados
DROP DATABASE nome_banco

-- Comando excluir tabelas
DROP TABLES nome_tabela

 

