-- COMANDOS PARA CRIAR UM BANCO DE DADOS
-- CREATE DATABASE ESCOLA_FRANZ;
-- CREATE DATABASE ESCOLA_FRANZ2;


-- COMANDO PARA APAGAR UM BANCO DE DADOS

-- DROP DATABASE ESCOLA_FRANZ2;

-- COMANDO PARA ATIVAR BANCO DE DADOS

-- USE ESCOLA_FRANZ;

-- CRIAR TABELAS
CREATE TABLE GESTAO_ESCOLAR (
ID_GESTAO INT AUTO_INCREMENT PRIMARY KEY,
OCORRENCIAS VARCHAR(100),
FINANCEIRO INT,
EVENTOS CHAR(15),
CARGO CHAR(20) DEFAULT "SECRETARIA"

);

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
CARGO CHAR(20) DEFAULT "PROFESSORES",
ESPECIALIDADE VARCHAR(20), 
BLOCO CHAR(7) NOT NULL,
NOME_INSPETOR VARCHAR(40) NOT NULL

);

CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME_ALUNO VARCHAR(40) NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
SERIE CHAR(10) NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS_ALUNO CHAR(10) DEFAULT "ATIVO",
RM INT NOT NULL UNIQUE

);
